name: 'extractSelenideScreenshot'
description: 'GitHub Action to extract base64 encoded screenshot taken by Selenide from logs'
author: 'm0rr1s-p'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'camera'
  color: 'green'

# Define your inputs here.
inputs:
  gh-token:
    required: true
    description: 'Github repo token'
  run-id:
    required: true
    description: 'Github run ID'
  job-name:
    required: true
    description: 'Current Job name'
  repo-owner:
    required: false
    description: 'Repo owner'
    default: ${{ github.repository_owner }}
  repo-name:
    required: false
    description: 'Repo name'
    default: ${{ github.repository }}

# Define your outputs here.



runs:
  using: node20
  main: dist/index.js
