name: bypass branch protection

on:
  push:
    branches:
      - 'bypass-branch-rule'

jobs:
  bypass:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
      - name: Git
        run: |
          echo ${{ github.ref_name }}
          echo "test-${{ github.run_id }}" >> __tests__/index.test.ts
          echo "test-${{ github.run_id }}" >> __tests__/index.tests.ts
          git config user.email "devops@mineral-minds.de"
          git config user.name "automation-mm"
          git add __tests__/index.test.ts __tests__/index.tests.ts
          git commit -m "version update"
          git push origin main
