name: bypass branch protection

on:
  push:
    branches:
      - 'bypass-branch-rule'

env:
  # Use the same ssh-agent socket value across all jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
      - name: Git
        run: |
          echo "test-${{ github.run_id }}" >> README.md
          git commit -m "test"
          git push