name: bypass branch protection

on:
  push:
    branches:
      - 'bypass-branch-rule'

env:
  # Use the same ssh-agent socket value across all jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
      - name: Git
        run: |
          echo "test-${{ github.run_id }}" >> README.md
          git config user.email "devops@mineral-minds.de"
          git config user.name "automation-mm"
          git add ./README.md
          git commit -m "test"
      - uses: ad-m/github-push-action@v0.8.0
        with:
          branch: main
          ssh: true