name: bypass branch protection

on:
  push:
    branches:
      - 'bypass-branch-rule'

jobs:
  bypass:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
      - name: Git
        run: |
          echo ${{ github.ref_name }}
          echo "test-${{ github.run_id }}" >> app/pom.xml
          git config user.email "devops@mineral-minds.de"
          git config user.name "automation-mm"
          git add app/pom.xml
          git commit -m "test"
          git push origin main
