name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - release/**
      - 'chore20250331'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  #test-typescript:
  #  name: TypeScript Tests
  #  runs-on: self-hosted
  #
  #  steps:
  #    - name: Checkout
  #      id: checkout
  #      uses: actions/checkout@v4
  #
  #    - name: Setup Node.js
  #      id: setup-node
  #      uses: actions/setup-node@v4
  #      with:
  #        node-version-file: .node-version
  #        cache: npm
  #
  #    - name: Install Dependencies
  #      id: npm-ci
  #      run: npm ci
  #
  #    #     - name: Check Format
  #    #       id: npm-format-check
  #    #       run: npm run format:check
  #
  #    - name: Lint
  #      id: npm-lint
  #      run: npm run lint
  #
  #    - name: Test
  #      id: npm-ci-test
  #      run: npm run ci-test
  #    - name: RUN ID
  #      run: echo "${{ github.run_id }}"

  test-action:
    #needs: test-typescript
    name: GitHub Actions Test
    runs-on: self-hosted

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: RUN ID
        run: echo "${{ github.run_id }}"
      - name: Test Local Action
        uses: ./
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          run-id: 14155493720
          job-name: 'tests_selenide'
          repo-name: 'mineralminds'
          repo-owner: 'Mineral-Minds-Deutschland'
          hosting-url: 'http://10.10.10.16:8081/api/1/upload' #${{ secrets.CHEVERETO_HOSTING_URL }}
          api-key: ${{ secrets.CHEVERETO_API_KEY }}
          images: './*.png'
      #- name: Test Remote Action
      #  uses: ./
      #  with:
      #    gh-token: ${{ secrets.GH_TOKEN }}
      #    run-id: 12748696601
      #    job-name: 'tests_selenide'
      #    repo-name: 'mineralminds'
      #    repo-owner: 'Mineral-Minds-Deutschland'
      #    hosting-url: ${{ secrets.CHEVERETO_HOSTING_URL }}
      #    api-key: ${{ secrets.CHEVERETO_API_KEY }}
      #    images: './*.png'
