name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - release/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: self-hosted

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

#     - name: Check Format
#       id: npm-format-check
#       run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
      - name: RUN ID
        run: echo "${{ github.run_id }}"

  test-action:
    needs: test-typescript
    name: GitHub Actions Test
    runs-on: self-hosted

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: RUN ID
        run: echo "${{ github.run_id }}"
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          run-id: 11387453682
          job-name: 'tests_selenide / tests_selenide'
          repo-name: 'planning'
          repo-owner: 'm0rr1s-p'
      - name: Cloudinary upload
        uses: emmanuelgautier/cloudinary-upload-action@v2.0
        with:
          cloud-name: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          api-key: ${{ secrets.CLOUDINARY_API_KEY }}
          api-secret: ${{ secrets.CLOUDINARY_API_SECRET }}
          images: "./*.png"
